db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: ${DB_PASSWORD}
liquibase:
  image: sequenceiq/liquibase
  links:
    - db
  volumes:
    - ./liquibase:/changelogs
  entrypoint: ''
  command:
    liquibase
      --changeLogFile=/changelogs/changelog.xml
      --username=postgres
      --password=${DB_PASSWORD}
      --url="jdbc:postgresql://db/postgres"
      --classpath=/opt/jdbc_drivers/postgresql-9.3-1102.jdbc41.jar
      update
app:
  build: .
  links:
    - db
  environment:
    DB_PASSWORD: ${DB_PASSWORD}
